#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
ROOT_DIR="$SCRIPT_DIR"
(
   cd "$ROOT_DIR" || exit
   ./mill cli.standaloneLauncher
)

echo ala > error.txt

"$ROOT_DIR/out/cli/standaloneLauncher/dest/launcher" "$@" 2> error.txt
